# Generated by Django 3.0.6 on 2020-08-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetitionForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], max_length=200)),
                ('stay', models.CharField(choices=[('Localite', 'Localite'), ('Hostalite', 'Hostalite')], max_length=100)),
                ('your_view_about_fee', models.TextField()),
            ],
        ),
    ]
